apiVersion: v1
kind: PersistentVolume
metadata:
 name: oke-fsspv
 namespace: wordpress
spec:
 storageClassName: oci-fss
 capacity:
  storage: 10Mi
 accessModes:
  - ReadWriteMany
 mountOptions:
  - nosuid
 nfs:
# Replace this with the IP of your FSS file system in OCI
  server: 10.0.10.220
# Replace this with the Path of your FSS file system in OCI
  path: "/wordpress-fss"
  readOnly: false
