kind: Service
apiVersion: v1
metadata:
  name: quickstart-mp
  labels:
    app: quickstart-mp
spec:
  type: NodePort
  selector:
    app: quickstart-mp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: quickstart-mp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart-mp
  template:
    metadata:
      labels:
        app: quickstart-mp
        version: v1
    spec:
      containers:
      - name: quickstart-mp
        image: quickstart-mp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
